
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bootiful-client
  description: API for customers
  tags:
    - java
    - spring-boot
    - web
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=bootiful-client'
spec:
  type: service
  lifecycle: experimental
  owner: group:labs-crew
  dependsOn:
    - component:bootiful-service
  providesApis:
    - bootiful-client.demo.apps.labs.tanzu.rocks
