---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: surferslookout-db
  #namespace: default
  description: Database service for SurfersLookout application
  annotations:
    backstage.io/kubernetes-id: surferslookout-db
    backstage.io/kubernetes-label-selector: 'app=surferslookout-db'
spec:
  type: service
  lifecycle: experimental
  owner: group:labs-crew
  system: labs-system
  dependencyOf:
    - component:surfersweb
        
---
