
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: surfersweb
  #namespace: default
  description: Web Frontend SurfersLookout application
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=surferslookout,component=frontend'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:labs-crew
  system: labs-system
  dependsOn:
    - component:surferslookout-db
    - component:surfersapi
  consumesApis:
    - surfersapi-tap3.tanzu.rocks
  